/* https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/

//Approach 1- sort the arrays- each take (n log n) and then compare O(n)

public class Solution {
    public char findTheDifference(String s, String t) {        
        char[] a=s.toCharArray();
        char[] b=t.toCharArray();        
        Arrays.sort(a);
        Arrays.sort(b);        
        int n=b.length;
        int i=0;
        while(i<n-1){
            if(a[i]==b[i])i++;                     
            else return b[i];
        }return b[i++];    
    }
}

//Metjod 2using xor bitwise O(n) timepublic class Solution {
    public char findTheDifference(String s, String t) {        
        char chk=0;
        for(int i=0;i<s.length();i++){
            char c=s.charAt(i);
            chk^=c;
        }
        for(int i=0;i<s.length();i++){
            char c=t.charAt(i);
            chk^=c;
        }
        return c;
    }
}

